server:
  port: 9202

service-url:
  user-service: http://localhost:8201

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
#      - id: path_rout
#        uri: ${service-url.user-service}/user/{id}
#        predicates:
#          - Path=/user/{id}
#          - Cookie=name,zz
#          - Host=www.baidu.com

#      - id: test_filter
#        uri: ${service-url.user-service}/user/{id}
#        filters:
##          - AddRequestParameter=name,ffff
#          - StripPrefix=1
#        predicates:
##          - Method=GET
#          - Path=/ff/**

        - id: hystrix_test
          uri: ${service-url.user-service}/user/{id}
          predicates:
            - Method=GET
          filters:
            - name: Hystrix
              args:
                name: fallbackcmd
                fallbackUri: forward:/fallback


#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8001/eureka/